# Browsersync config
BROWSERSYNC:
  # URL of local development server goes here (ex. http://localsite.dev)
  url: "https://docker.test"

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "assets"
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "build/**/*"
    - "!build/{img,js,sass}/**/*"
    - "node_modules/jplayer/dist/jplayer/jquery.jplayer.swf"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "node_modules/foundation-sites/scss"
    - "node_modules/motion-ui/src"
  # Paths to SCSS and JavaScript entry points
  entries:
    scss: 
      - "build/sass/app.scss"
      - "build/sass/admin.scss"
    js: 
      - "build/js/app.js"
      - "build/js/admin.js"

# Set to true if you want static asset revisioning, helpful for cache busting
REVISIONING: false    